function p = wp2_parameterGen(fs,varargin)
%wp2_parameterGen       Generate a suitable parameter structure from a
%                       user-provided list of parameter names and values.
%                       Calling the function with no argument will list the
%                       existing parameters with their default values
%
%USAGE:
%   p = wp2_parameterGen()  
%   p = wp2_parameterGen(fs,'name1',value1,...,'nameN','valueN');
%
%INPUT ARGUMENTS:
%      fs : Sampling frequency (Hz)
% 'nameN' : Valid parameter name (string)
%  valueN : Valid value for parameter 'nameN'
%
%OUTPUT ARGUMENTS:
%       p : Parameter structure

if nargin == 0
    % Display a list of available parameters as implemented in 
    % 'getDefaultParameters.m'
    p_def = getDefaultParameters(1,'processing');
    
    % Get the parameter names
    names = fieldnames(p_def);
    
    % Description of each parameter
    description = {'Sampling frequency (Hz)',...
        'Lowest center frequency (Hz)',...
        'Highest center frequency (Hz)',...
        'Gammatone filter type (''IIR'' or ''FIR'')',...
        'Distance between neighbor filters (ERBs)',...
        'Rising slope order',...
        'Filters bandwidth (ERBs)',...
        'Decimation ratio in the filterbank',...
        'Duration of the FIR (s)',...
        'Correction for filter alignment (true or false)',...
        'IHC model',...
        'Window name',...
        'Window duration (s)',...
        'Window step size (s)',...
        'Window name',...
        'Window duration (s)',...
        'Window step size (s)',...
        'Ratemap scaling (''power'' or ''magnitude'')',...
        'Leaky integrator time constant (s)',...
        'Window name',...
        'Window duration (s)',...
        'Window step size (s)',...
        'Center clipping method (''clc'',''clp'',''sgn'')',...
        'Threshold in center clipping (re. 1)',...
        'Exponent in auto-correlation',...
        'Window name',...
        'Window duration (s)',...
        'Window step size (s)',...
        'Maximum delay in cross-correlation (s)'};
    
    % Separate parameters in categories
    cat_labels = {'General',...
        'Gammatone filterbank',...
        'Inner hair-cell envelope',...
        'Interaural level difference (ILD)',...
        'Ratemap',...
        'Auto-correlation',...
        'Cross-correlation'};
    cat_indexes = [1 2 11 12 15 20 26];
    
    % List of parameters not to display (e.g. not yet implemented)
    dontDisp = [1 5 7 9];
    
    % Display a short header
    fprintf('The following parameters can be involved in WP2 processing:\n\nExact name (default value) : Description\n\n')
    
    % Display the information
    for ii = 1:size(description,2)
        
        if ~ismember(ii,dontDisp)
            fprintf('%s (%s) : \t\t%s\n',names{ii},num2str(p_def.(names{ii})),description{ii})
        end        
    end
        
    
    
    
end



% Populate the parameter structure





